name: gcanvas
version: 0.0.6
author: James Hurford <terrasea@gmail.com>
description: Canvassing App for doorknocking campaigns.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser_detect: any
  core_elements: any
  csvparser: any
  lawndart: any
  oauth2: any
  paper_elements: any
  polymer: '>=0.12.1 <0.13.0'
  route_hierarchical: any
  uuid: any
dev_dependencies:
  scheduled_test: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    lint: 'false'
