name: gcanvas
version: 0.0.6
author: James Hurford <terrasea@gmail.com>
description: Canvassing App for doorknocking campaigns.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: "0.26.1+14"
  browser_detect: any
  csvparser: any
  lawndart: any
  oauth2: any
  polymer_elements: ">=1.0.0-rc.2 <2.0.0"
  polymer: ">=1.0.0-rc.2 <2.0.0"
  web_components: ">=0.12.0+3 <1.0.0"
  reflectable: ">=0.3.3 <1.0.0"
  polymer_interop: ">=1.0.0-rc.1 <2.0.0"
  route_hierarchical: any
  uuid: any
  dart_to_js_script_rewriter: any
dev_dependencies:
  test: any
transformers:
- web_components:
    entry_points:
    - web/index.html
    - test/index.html
- reflectable:
    entry_points:
    - web/main.dart
    - test/test.dart
- test/pub_serve:
    $include: test/test.dart
- $dart2js:
    minify: false
- dart_to_js_script_rewriter
