name: gcanvas
description: Canvasing App
dependencies:
  browser: any
  polymer: any
  lawndart: any
  angular: any
  angular_node_bind: any
dev_dependencies:
  unittest: any
transformers:
  - polymer:
      entry_points: web/index.html
