name: gcanvas
version: 0.0.5
author: James Hurford <terrasea@gmail.com>
description: Canvasing App for doorknocking campaigns.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: any
  lawndart: any
  polymer: any
  polymer_elements: any
  uuid: any
dev_dependencies:
  scheduled_test: any
transformers:
- polymer:
    entry_points:
    - web/index.html
- $dart2js:
    minify: false
