name: gcanvas
version: 0.0.5
author: James Hurford <terrasea@gmail.com>
description: Canvasing App for doorknocking campaigns.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser_detect: any
  csvparser: any
  http: any
  http_server: any
  lawndart: any
  mime: any
  polymer: '>=0.10.0 <0.11.0'
  postgresql: any
  route: any
  uuid: any
dependency_overrides:
  polymer_expressions: '>=0.11.0 <0.12.0'
dev_dependencies:
  scheduled_test: any
transformers:
- polymer:
    entry_points:
    - web/index.html
