name: gcanvas
version: 0.0.5
author: James Hurford <terrasea@gmail.com>
description: Canvasing App for doorknocking campaigns.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  csvparser: any
  http: any
  http_server: any
  lawndart: any
  mime: any
  polymer: '>=0.10.0-pre.13 <0.11.0'
  polymer_ui_elements:
    git: https://github.com/terrasea/polymer_ui_elements.git
    version: 0.2.0-pre.8.terrasea.1
  postgresql: any
  route: any
  uuid: any
dev_dependencies:
  scheduled_test: any
transformers:
- polymer:
    entry_points:
    - web/index.html
